version: "3.7"
services:
  postgres_db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    privileged: true
    ports:
      - 5432:5432
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres