version: "3.7"
services:
  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    privileged: true
    ports:
      - 3306:3306
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root